language: node_js
node_js:
- node
cache: npm
install:
- npm ci
- npm install -g firebase-tools
script:
- npm run build
- npm run lint
after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN
notifications:
  email: false

travis:
  secure: ToAYWlFGuwLDcGY7+qUHctB6zJiQMFqOXhOIvwrFL+UuPikd8qDUvq7Z7FCyzKIQ5AH2n7/gk4KdWiu1GAKieYj7Yh7eFWwXcHfVxQAQK2FGW7+zfZYLC4GAO0KHagyRJVnk5VvtzL4eITaL+hmZeagvHy9ZUBtjmLdWFRplLTubGmzG9rPxDuBxOyrcHeYQQp0xodBui47s4cCswcpBEcEHAdjllIbID1L4sDK5vtI5HMmduhZWkyvIaT0z0qtBxv7Y53QMM0PxGE55FHVaffih0SH8T5YVv5AFl3bOyF+OKKBxqGy71pjsmzvjcYjfWNTJmN+ocGiCdmAqNoSlVvrexa81YFKBkmNLis5JlX/g3AbvP0UyjgIDKVHgLwgyxaRBWCzD3VrYEhnIwmfh3N/2NFpgU9IjfR5/Vri+gxtDkI1uSTimG5Zh9exlNcgusGbsk5U8DUWdJQtPppdB3/BGs99yDBYrM7IEc6TMN00wrIUhbmzg79o52s822D0fvhIYqsEGKjez16zwbeSKjMbaekn5koprXuYOpBejTwhZMPOMC+5YeoqAIpm57+E7RCb03CITiE7xjj8eM96bGkmGC+2glvMkQnCr7gUrvkOpK6OZBBRZBDSRcDbjt+K7NcHENr0UjpLdHMTJsp+zOyZWRlNA0KI8BQ5wElT/Z8w=
