language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - ".firebase"
install:
- npm ci
script:
- npm run build
- npm run lint
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
  token:
    secure: OC7+Qe45u9/PVjnBocujT3NxDexgW/t6ygz8jpu6HSDD8OgDi9U4kVi49C+NwFz83wLWvDQLHiwQSYkD/iyBY8j8V7jW2wOua4S9iuaDQc7gnpdWsNsXVkacaOqcLLs+idyG0sc7+KWsLLSrOIwxSkTT8bP8j7fPWQwUcVHBYyDunFQfuXr9DMnfIwj0mJLk7Y0eASLWBG2n6LaUW1C3Uf+BTadF8FbcjiRAHkTfrmGV85DBBdra31Z5qoW3vJ3WwFHp1lSUKjQdYJjHyzd6kAirQTQkud+dj+kr6bDTj9R73y6Fwzj9VmARsU6LHgsoRQvFIrA+z5HSCBT/M2FoBn/qUaIQjGMkZSjJ6AthxHn21Nfjiv06Ca53LsibOp3MuI/15RZ1UbhPXaWgr3bGZpWIGfOk7m/d+4mZ9xb0u+7ycFL2z8e8RHiJCsuLeuI+0cEW3+F851eLOmbIW585TMmM4RlimzarC0dsgy3F6gBOHkdtAxwoNnkV+AX8ANxmaXDPt6Haz6YgfLD1Jlf5FyVBovd60mDyq8l2naFDt5cu61Yu84CMz5O/AJhPfBBw/mRpXpxScC9HCKlcm6rqCZ/DAIHoP4DCStHZmPu82xo66UKL1twwPbqIPHuSYPE6yFSxwUVeYREwdcwzX745w9XZtV/cL4+cuKLfSQ3/Q9c=
notifications:
  email: false
